id: IA2D3EDA4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T16:27:50+00:00'
last_modified: '2022-06-08T16:23:52.950655+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20113
  title: སྟོན་བཤད་སྐྱིད་གཡང་དགའ་འཁྱིལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '4181':
      image_group_id: I4760
      title: ''
      total_pages: 270
      order: 1
      base_file: 4181.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
